export enum Feature {
  Rooms = "Rooms",
  Bathrooms = "Bathrooms",
  ParkingSlots = "ParkingSlots",
  LandingSize = "LandingSize",
  ShowerHead = "ShowerHead",
  AirConditioning = "snowflake",
  SwimmingPool = "swimming-person",
  YogaArea = "lotus",
  PetFriendlyArea = "dog",
  CommonAreas = "users",
  SunbathingArea = "sun",
  OutdoorBathroom = "tree-pine",
  StorageRoom = "box",
  GolfCourse = "golf",
  SoccerField = "goal",
  PaddleCourt = "tennis",
  TennisCourt = "tennis",
  Cinema = "clapperboard",
  CoworkingSpace = "laptop",
  EquippedKitchen = "utensils",
  ConciergeService = "concierge-bell",
  ServiceRoom = "door-open",
  Elevator = "arrow-up-down",
  Parking = "car",
  BeachFront = "umbrella",
  Gym = "dumbbell",
  Jacuzzi = "bath",
  Garden = "sprout",
  Laundry = "washer",
  Microwave = "microwave",
  Grill = "grill",
  Patio = "home",
  PoolBar = "cocktail",
  Refrigerator = "refrigerator",
  RoofGarden = "tree-palm",
  MultipurposeRoom = "layout-grid",
  Sauna = "thermometer",
  Dryer = "circle-slashed",
  RoundTheClockSecurity = "shield-check",
  Spa = "leaf",
  Terrace = "sunset",
  CableTV = "tv",
  OceanView = "waves",
  WiFi = "wifi"
}

export interface PropertyFeature {
  type: keyof typeof Feature;
  value: number | string;
}
