import {
  AirVent,
  Waves,
  Activity,
  PawPrint,
  Users,
  Sun,
  Bath,
  Archive,
  Flag,
  LandPlot,
  Film,
  Briefcase,
  Utensils,
  ConciergeBell,
  BedDouble,
  MoveDown,
  Car,
  Dumbbell,
  ShowerHead,
  TreeDeciduous,
  WashingMachine,
  Microwave,
  Flame,
  LayoutDashboard,
  Wine,
  Refrigerator,
  Sprout,
  DoorOpen,
  ThermometerSun,
  Wind,
  ShieldCheck,
  Sparkles,
  Landmark,
  Tv,
  Binoculars,
  Wifi,
  LucideIcon
} from "lucide-react";

export const amenityIcons: Record<string, LucideIcon> = {
  AirConditioning: AirVent,
  SwimmingPool: Waves,
  YogaArea: Activity,
  PetFriendlyArea: PawPrint,
  CommonAreas: Users,
  SunbathingArea: Sun,
  OutdoorBathroom: Bath,
  StorageRoom: Archive,
  GolfCourse: Flag,
  SoccerField: LandPlot,
  PaddleCourt: LandPlot,
  TennisCourt: LandPlot,
  Cinema: Film,
  CoworkingSpace: Briefcase,
  EquippedKitchen: Utensils,
  ConciergeService: ConciergeBell,
  ServiceRoom: BedDouble,
  Elevator: MoveDown,
  Parking: Car,
  BeachFront: Waves,
  Gym: Dumbbell,
  Jacuzzi: ShowerHead,
  Garden: TreeDeciduous,
  Laundry: WashingMachine,
  Microwave,
  Grill: Flame,
  Patio: LayoutDashboard,
  PoolBar: Wine,
  Refrigerator,
  RoofGarden: Sprout,
  MultipurposeRoom: DoorOpen,
  Sauna: ThermometerSun,
  Dryer: Wind,
  RoundTheClockSecurity: ShieldCheck,
  Spa: Sparkles,
  Terrace: Landmark,
  CableTV: Tv,
  OceanView: Binoculars,
  WiFi: Wifi
};
