import { ComparisonSection } from "@/types/plan-info";
import {
  BellIcon,
  BellPlusIcon,
  BellRingIcon,
  BotIcon,
  CameraIcon,
  ChartLineIcon,
  ChartPieIcon,
  CircleCheckBigIcon,
  CircleDotIcon,
  CircleHelpIcon,
  DownloadIcon,
  FileScanIcon,
  ForwardIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeadphonesIcon,
  HeadsetIcon,
  HeartIcon,
  LaptopIcon,
  LightbulbIcon,
  MessageCircleIcon,
  PackageOpenIcon,
  PencilIcon,
  PuzzleIcon,
  RefreshCcwIcon,
  SaveIcon,
  SearchIcon,
  SendIcon,
  Share2Icon,
  StarIcon,
  UserIcon,
  UsersIcon,
  WandIcon,
} from "lucide-react";

export const pricingInfo: Array<ComparisonSection> = [
  {
    title: "PERFILES",
    items: [
      {
        Icon: UserIcon,
        Information: CircleHelpIcon,
        infoDescription: "Número de asientos a la que una cuenta tiene acceso.",
        name: "Número de usuarios",
        free: "1",
        agent: "1",
        agency: "1-4",
        agencyVIP: "1-10",
      },
      {
        Icon: SearchIcon,
        name: "Optimización SEO de tu perfil",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: MessageCircleIcon,
        name: "WhatsApp en tu perfil",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: PencilIcon,
        name: "Descripción y experiencia",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
    ],
  },
  {
    title: "PUBLICAR ANUNCIOS",
    items: [
      {
        Icon: CircleCheckBigIcon,
        name: "Publicaciones propiedades",
        free: "1",
        agent: "Ilimitadas",
        agency: "Ilimitadas",
        agencyVIP: "Ilimitadas",
      },
      {
        Icon: BotIcon,
        name: "Creditos IA",
        free: "Limitado para 1 anuncio",
        agent: "Ilimitadas",
        agency: "Ilimitadas",
        agencyVIP: "Ilimitadas",
      },
      {
        Icon: CameraIcon,
        name: "Fotos / anuncios",
        free: "5",
        agent: "Ilimitadas",
        agency: "Ilimitadas",
        agencyVIP: "Ilimitadas",
      },
      {
        Icon: FileScanIcon,
        name: "Fichas técnicas con QR único",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: SearchIcon,
        name: "Optimización SEO de tus anuncios",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: PackageOpenIcon,
        name: "Migración de tus propiedades",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
    ],
  },
  {
    title: "VISIBILIDAD",
    items: [
      {
        Icon: GlobeIcon,
        name: "Publicación en Francia y Canadá",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: StarIcon,
        name: "Anuncios destacados / mes",
        free: false,
        agent: "3",
        agency: "8",
        agencyVIP: "12",
      },
      {
        Icon: ForwardIcon,
        name: "Comparte tus anuncios en tus redes sociales",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
    ],
  },
  {
    title: "WHITE LABEL",
    items: [
      {
        Icon: LaptopIcon,
        name: "Sitio Web profesional",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: WandIcon,
        name: "Template de Sitio Web",
        free: false,
        agent: "3",
        agency: "3",
        agencyVIP: "3",
      },
    ],
  },
  {
    title: "MULTI PORTALES",
    items: [
      {
        Icon: Share2Icon,
        name: "Difusión en otros portales inmobiliarios",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
    ],
  },
  {
    title: "LEADS",
    items: [
      {
        Icon: UsersIcon,
        name: "Migración de contactos",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: SendIcon,
        name: "Envío de anuncios a leads registrados",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: CircleDotIcon,
        name: "Hasta 10 leads de compradores al mes",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
    ],
  },
  {
    title: "SOPORTE & GESTIÓN",
    items: [
      {
        Icon: HeadsetIcon,
        name: "Soporte dedicado",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: ChartPieIcon,
        name: "Estadísticas",
        free: "Demo",
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: ChartLineIcon,
        name: "CRM",
        free: "Demo",
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: GraduationCapIcon,
        name: "Academia",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: RefreshCcwIcon,
        name: "Renovación automática",
        free: false,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: MessageCircleIcon,
        name: "Grupo Whatsapp HomLista",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: HeadphonesIcon,
        name: "Discord",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
    ],
  },
  {
    title: "ANUNCIOS",
    items: [
      {
        Icon: SaveIcon,
        name: "Guardar anuncios",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: MessageCircleIcon,
        name: "Contactar un asesor / agencia",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: LightbulbIcon,
        name: "Recibir sugerencias",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: BellIcon,
        name: "Alerta de búsqueda",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: BellPlusIcon,
        name: "Crear alerta de búsqueda",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: HeartIcon,
        name: "Liker y compartir anuncios",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: UsersIcon,
        name: "Ver perfil de asesores / agencias",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: StarIcon,
        name: "Valorar y recomendar",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: DownloadIcon,
        name: "Descargar ficha técnica",
        free: true,
        agent: true,
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: BellRingIcon,
        name: "Alertas priorizadas",
        free: false,
        agent: 'Con un plan "Comprador"',
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: PuzzleIcon,
        name: "Matching personalizado",
        free: false,
        agent: 'Con un plan "Comprador"',
        agency: true,
        agencyVIP: true,
      },
      {
        Icon: BotIcon,
        name: "Acceso a un asistente de IA de búsqueda",
        free: false,
        agent: 'Con un plan "Comprador"',
        agency: true,
        agencyVIP: true,
      },
    ],
  },
];
