import { Property } from "@/types/property";

export const properties: Array<Property> = [
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "ForSale",
    title: "Propiedad 1",
    location: "Ciudad de México",
    price: { currency: "MXN", value: 2000000 },
    features: [
      { type: "Bathrooms", value: 2 },
      { type: "LandingSize", value: 200 },
    ],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "Rent",
    title: "Propiedad 2",
    location: "Guadalajara",
    price: { currency: "MXN", value: 15000 },
    features: [{ type: "Rooms", value: 3 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Offer",
    transaction: "ForSale",
    title: "Propiedad 3",
    location: "Monterrey",
    price: { currency: "MXN", value: 5000000 },
    features: [{ type: "Bathrooms", value: 4 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "Rent",
    title: "Propiedad 4",
    location: "Puebla",
    price: { currency: "MXN", value: 12000000 },
    features: [
      { type: "Rooms", value: 2 },
      { type: "LandingSize", value: 100 },
    ],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "ForSale",
    title: "Propiedad 5",
    location: "Tijuana",
    price: { currency: "MXN", value: 3000000 },
    features: [{ type: "Bathrooms", value: 3 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Offer",
    transaction: "Rent",
    title: "Propiedad 6",
    location: "Cancún",
    price: { currency: "MXN", value: 25000 },
    features: [{ type: "Rooms", value: 4 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "ForSale",
    title: "Propiedad 7",
    location: "Querétaro",
    price: { currency: "MXN", value: 1800000 },
    features: [{ type: "Bathrooms", value: 2 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "Rent",
    title: "Propiedad 8",
    location: "Mérida",
    price: { currency: "MXN", value: 10000 },
    features: [{ type: "Rooms", value: 1 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Offer",
    transaction: "ForSale",
    title: "Propiedad 9",
    location: "Toluca",
    price: { currency: "MXN", value: 4000000 },
    features: [{ type: "Bathrooms", value: 3 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "Rent",
    title: "Propiedad 10",
    location: "León",
    price: { currency: "MXN", value: 14000 },
    features: [{ type: "Rooms", value: 3 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "ForSale",
    title: "Propiedad 11",
    location: "Aguascalientes",
    price: { currency: "MXN", value: 2200000 },
    features: [{ type: "Bathrooms", value: 2 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Offer",
    transaction: "Rent",
    title: "Propiedad 12",
    location: "Chihuahua",
    price: { currency: "MXN", value: 20000 },
    features: [{ type: "Rooms", value: 4 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "ForSale",
    title: "Propiedad 13",
    location: "Saltillo",
    price: { currency: "MXN", value: 3500000 },
    features: [{ type: "Bathrooms", value: 3 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "Rent",
    title: "Propiedad 14",
    location: "Morelia",
    price: { currency: "MXN", value: 11000 },
    features: [{ type: "Rooms", value: 2 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Offer",
    transaction: "ForSale",
    title: "Propiedad 15",
    location: "Hermosillo",
    price: { currency: "MXN", value: 4500000 },
    features: [{ type: "Bathrooms", value: 4 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "Rent",
    title: "Propiedad 16",
    location: "Culiacán",
    price: { currency: "MXN", value: 13000 },
    features: [{ type: "Rooms", value: 3 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "ForSale",
    title: "Propiedad 17",
    location: "Mazatlán",
    price: { currency: "MXN", value: 2800000 },
    features: [{ type: "Bathrooms", value: 2 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Offer",
    transaction: "Rent",
    title: "Propiedad 18",
    location: "San Luis Potosí",
    price: { currency: "MXN", value: 18000 },
    features: [{ type: "Rooms", value: 4 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "ForSale",
    title: "Propiedad 19",
    location: "Veracruz",
    price: { currency: "MXN", value: 3200000 },
    features: [{ type: "Bathrooms", value: 3 }],
  },
  {
    image: "https://pics.craiyon.com/2024-04-22/d25WiRyTTnazlHfrKYp2HA.webp",
    tag: "Featured",
    transaction: "Rent",
    title: "Propiedad 20",
    location: "Oaxaca",
    price: { currency: "MXN", value: 9000 },
    features: [{ type: "Rooms", value: 1 }],
  },
];
