name: Chromatic Deployment

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: |
          # Create minimal package.json for submodule if it doesn't exist
          if [ ! -f "src/shared/package.json" ]; then
            echo '{"name": "@team-homlista/shared_components", "version": "0.0.0", "main": "components/ui/index.tsx"}' > src/shared/package.json
            echo "Created minimal package.json for submodule"
          fi
          
          npm install --frozen-lockfile
          
          # Force re-link workspace to ensure submodule is accessible
          npm install --force-local-workspace-links
          
          # Debug: Check submodule content
          echo "=== Checking submodule status ==="
          git submodule status
          echo "=== Checking if story file exists ==="
          ls -la src/shared/components/ui/ | grep stories || echo "No stories found in submodule"
          echo "=== Checking story pattern match ==="
          find src -name "*.stories.*" -type f
          echo "=== Checking workspace linking ==="
          ls -la node_modules/@team-homlista/ || echo "Workspace not linked"
          echo "=== Testing story file readability ==="
          cat src/shared/components/ui/button.stories.tsx | head -5 || echo "Cannot read story file"
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}