name: Chromatic Deployment

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  deploy-chromatic:
    continue-on-error: true
    if: contains(github.event.pull_request.labels.*.name, 'chromatic-deployment')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm build-storybook
      - name: Run Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes --storybook-build-dir=storybook-static
        env:
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha }}
          CHROMATIC_BRANCH: ${{ github.head_ref }}