name: Chromatic Deployment

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          # Use a PAT with read access to the submodule if needed
          # token: ${{ secrets.SUBMODULES_TOKEN }}

      - name: Sync & init submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          git submodule status --recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Install dependencies
        run: npm install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}