name: Chromatic Deployment

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  deploy-chromatic:
    continue-on-error: true
    if: contains(github.event.pull_request.labels.*.name, 'chromatic-deployment')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm ci
          npm run build-storybook
      - name: Run Chromatic
        run: npx chromatic -project-token $secrets.CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes